### ISSUE TITLE
Errors when using shell script and goss directly

### ISSUE THREAD

**Issue by claremont-awilson** [ansible-lockdown/RHEL8-CIS-Audit#73]
**Describe the Issue**
Running goss directly does not work, get an error about the machine_uuid:

`/usr/local/bin/goss --vars vars/CIS.yml -g /opt/RHEL8-CIS-Audit/goss.yml validate`

> Error: template: test:57:33: executing "test" at <.Vars.machine_uuid>: map has no entry for key "machine_uuid"

**Expected Behavior**
Expected it to run

**Actual Behavior**
Errors about machine_uuid even though I can manually run the check taken from the run_audit.sh script it works fine.

e.g. 
```
host_machine_uuid="$(if [ -f /sys/class/dmi/id/product_uuid ]; then cat /sys/class/dmi/id/product_uuid; else dmidecode -s system-uuid; fi)"
echo $host_machine_uuid
```

> b528fc23-1df3-4605-b553-1b747abcb1d2

**Control(s) Affected**
All of them

**Environment (please complete the following information):**

- goss version: v0.4.9
- OS version: Oracle Linux 8.10
- Additional Details:

**Additional Notes**
I get a different error when trying to run it using the provided run_audit.sh script:

> ## Pre-Checks Start
> 
> OK - Audit binary /usr/local/bin/goss is available
> OK - Goss is installed and version is ok (0.4.9 >= 0.3.21)
> OK - /opt/RHEL8-CIS-Audit/goss.yml is available
> 
> ## Pre-checks Successful
> 
> #############
> Audit Started
> #############
> 
> 2025-02-13T14:14:28Z [WARN] Duplicate key detected: 'mount: /tmp'. The value from a later-loaded goss file has overwritten the previous value.
> Completed file can be found at /opt/audit_cloudstacktest.claremont.co.uk-CIS-RHEL8_1739456068.json
> ###############
> Audit Completed
> ###############

The contents of the JSON file are:

> 
> Error: could not read json data in /opt/RHEL8-CIS-Audit/section_1/cis_1.1/cis_1.1.3.2_4.yml: yaml: unmarshal errors:
>   line 11: mapping key "opts" already defined at line 10

**Comment by uk-bolly** [comment]
hi @claremont-awilson 

Thank you for the issue and details provided.
There are a couple of points which i believe are in the readthedocs but i will add here.

- goss.yml is setup to be used by the run_audit script as the script creates some extra meta data that is used as server identifiable data, that will be the reason for the uuid 
  - If you wish to run witout the script you need to remove the sections toward the bottom of the goss.yml where the extra meta fields are added
- Branch naming is very important, if you could let us know which branch you are using or which version are the benchamrk you are hoping to audit?
  -  I would suggest you use one named benchmark_vxxxx 

Be keen to find out the branch you are using as they should work as expected.

kindest regards

uk-bolly

**Comment by claremont-awilson** [comment]
Hello,
          Thanks for getting back to me.

I've removed:
```
    meta:
      host_machine_uuid: {{ .Vars.machine_uuid }}
      host_epoch: {{ .Vars.epoch }}
      host_os_locale: {{ .Vars.os_locale }}
      host_os_release: {{ .Vars.os_release }}
      host_os_distribution: {{ .Vars.os_distribution }}
      host_automation_group: {{ .Vars.auto_group }}
      host_hostname: {{ .Vars.os_hostname }}
      host_system_type: {{ .Vars.system_type }}
      benchmark_type: {{ .Vars.benchmark_type }}
      benchmark_version: {{ .Vars.benchmark_version }}
      benchmark_os: {{ .Vars.benchmark_os }}
```
from the end of goss.yml and running the run_audit.sh script generates the same warning and content in the JSON file.

 I've got an error running it with the script provided and I've tried it without the script provided using the goss binary directly, neither work. I don't really care which way does work, as long as it does to be honest.

Intending to run against CIS v2.0.0, bundled with the download at: https://github.com/ansible-lockdown/RHEL8-CIS-Audit.git located in the vars/CIS.yml file.

Thanks,


Ally
